### ISSUE TITLE
Troop allocation counter

### ISSUE THREAD

**Issue by hurstj22** [kramis24/RiskProjectGroup4#4]
It may be beneficial to include a small counter that displays how many troops a player is going to receive at the beginning of their next turn so that they can plan accordingly.

**Comment by benning23** [comment]
The troop count is shown for each player at the beginning of their turn. It can't be determined before that as an enemy may take over some of your territories during your turn therefore diminishing your troop count. It much easier just to display it at the beginning of a player's turn, and I don't see a lot of benefit to showing what they might have in the future
